### ISSUE TITLE
Mise à jour de la roadmap projet

### ISSUE THREAD

**Issue by tecuzin** [cavmandos/P6#16]

**Comment by cavmandos** [comment]
S35 : CRUD Trick -> Read

- [ ] Create 2/3 tricks
- [ ] Read : published/updated date
- [ ] Read : Group trick
- [ ] Relations Media/Trick
- [ ] Create 2/3 medias
- [ ] Read : Trick pictures
- [ ] Read : Trick videos
- [ ] Display buttons if connected

**Comment by cavmandos** [comment]
S36 : CRUD Trick -> Create

- [ ] Create a trick without media
- [ ] Media -> set type of media with url
- [ ] Create a trick + media
